site_name: UD
pages:
    - [index.md, Welcome]
    - [git.md, Git Utils]
    - [grunt.md, Grunt Utils]
    - [mongodb.md, Mongo DB Utils]
    - [laravel.md, Laravel Utils]
    - [ethmining.md, Eth Mining]

theme: readthedocs
extra_css: [extra.css]
